### ISSUE TITLE
"can't convert null to object" in Firefox

### ISSUE THREAD

**Issue by EhsanKia** [dfcreative/mucss#3]
This is a non-breaking bug, but I have my console spammed with

`TypeError: can't convert null to object`

on this line:
https://github.com/dfcreative/mucss/blob/master/prefix.js#L9

in Firefox. I'm 90% sure it's this bug here:
https://bugzilla.mozilla.org/show_bug.cgi?id=548397

Basically, `styles` is Null and it throws an error on the next line.
By any chance, could you just add a graceful exit line for this case?

**Comment by dy** [comment]
I’ve added a condition, now it should not bother you.
But I could not reproduce that error, the case where `document` has no `styles` is quite weird, I would recommend you to look up for error somewhere else in code.

**Comment by EhsanKia** [comment]
Thank you for the rapid response!
Tiny problem, I think you're missing a return at the end of that if statement, as right now it keeps going.
But I just tried it with the return locally and it does fix my issue.

It's definitely an edge case. I'm currently working on an extension for Twitch.tv which has loads of iframes, and as I mentioned above, it's a specific Firefox bug which shouldn't be happening.

**Comment by dy** [comment]
I see. Fixed.
